# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build_fish:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    macos:
        xcode: "14.2.0"
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: install dependencies
          command: "brew install cmake rust ninja llvm dmd zstd crystal"
      - run:
          name: install pexpect
          command: "pip3 install pexpect"
      - run:
          name: shards install
          command: "shards install --production"
      - run:
          name: crystal build
          command: "crystal build src/invidious.cr --release --static"
      - run:
          name: compress (tar)
          command: "tar -cvzf invidious.tar ./invidious"
      - run:
          name: compress (zstd)
          command: "zstd invidious.tar.zst"
      - store_artifacts:
          path: ./fish_shell.tar.zst
          destination: fish-shell.tar.zst

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  fish_workflow:
    jobs:
      - build_fish